// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eclrjzypacapggwkwbwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjbHJqenlwYWNhcGdnd2t3YndiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzIzOTksImV4cCI6MjA2MTc0ODM5OX0.I2iw_uBpbY_1etECxM4PccztPufPP3v16eTpkf0vKO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);